{
 "title": "Docker Dashboard",
 "tags": [ "docker" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(container_memory_usage_bytes, container_label_cc_bdp_lain_deployd_pg_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}) / max(container_spec_memory_limit_bytes{container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current"
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current"
  },
  {
   "title": "Container Running Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{image!=\"\", name!=\"swarm-agent.service\", name!=\"swarm-manager.service\", name!=\"calico-libnetwork\", name!=\"cadvisor.service\", name!=\"calico-node\", name!=\"rebellion.service\", container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}",
     "legendFormat": "{{instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\", image!=\"\", name!=\"swarm-agent.service\", name!=\"swarm-manager.service\", name!=\"calico-libnetwork\", name!=\"cadvisor.service\", name!=\"calico-node\", name!=\"rebellion.service\"}[1m])) by (name,instance))",
     "legendFormat": "{{instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\", image!=\"\", name!=\"swarm-agent.service\", name!=\"swarm-manager.service\", name!=\"calico-libnetwork\", name!=\"cadvisor.service\", name!=\"calico-node\", name!=\"rebellion.service\"}) by (name,instance))",
     "legendFormat": "{{instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name,instance) (rate(container_network_receive_bytes_total{container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\", image!=\"\", name!=\"swarm-agent.service\", name!=\"swarm-manager.service\", name!=\"calico-libnetwork\", name!=\"cadvisor.service\", name!=\"calico-node\", name!=\"rebellion.service\"}[1m] ) ))",
     "legendFormat": "{{instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name,instance) (rate(container_network_transmit_bytes_total{container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\", image!=\"\", name!=\"swarm-agent.service\", name!=\"swarm-manager.service\", name!=\"calico-libnetwork\", name!=\"cadvisor.service\", name!=\"calico-node\", name!=\"rebellion.service\"}[1m] ) ))",
     "legendFormat": "{{instance}} {{ name }}"
    }
   ]
  }
 ]
}