{
 "title": "Docker Dashboard",
 "description": "Mainly for Lain",
 "tags": [
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "label_values(container_memory_usage_bytes, container_label_cc_bdp_lain_deployd_pg_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Container Running Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{image!=\"\", name!=\"swarm-agent.service\", name!=\"swarm-manager.service\", name!=\"calico-libnetwork\", name!=\"cadvisor.service\", name!=\"calico-node\", name!=\"rebellion.service\", container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", name!=\"swarm-agent.service\", name!=\"swarm-manager.service\", name!=\"calico-libnetwork\", name!=\"cadvisor.service\", name!=\"calico-node\", name!=\"rebellion.service\", container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}[1m])) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\", name!=\"swarm-agent.service\", name!=\"swarm-manager.service\", name!=\"calico-libnetwork\", name!=\"cadvisor.service\", name!=\"calico-node\", name!=\"rebellion.service\", container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\", name!=\"swarm-agent.service\", name!=\"swarm-manager.service\", name!=\"calico-libnetwork\", name!=\"cadvisor.service\", name!=\"calico-node\", name!=\"rebellion.service\", container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\", name!=\"swarm-agent.service\", name!=\"swarm-manager.service\", name!=\"calico-libnetwork\", name!=\"cadvisor.service\", name!=\"calico-node\", name!=\"rebellion.service\", container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}