{
 "title": "Docker Dashboard",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(machine_memory_bytes, instance)"
   },
   {
    "name": "namespace",
    "query": "label_values(container_memory_usage_bytes, container_label_cc_bdp_lain_deployd_pg_namespace)"
   },
   {
    "name": "name",
    "query": "label_values(container_memory_usage_bytes, container_label_cc_bdp_lain_deployd_pg_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\", instance=~\"$server\",container_label_cc_bdp_lain_deployd_pg_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", instance=~\"$server\",container_label_cc_bdp_lain_deployd_pg_namespace=~\"$namespace\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\", instance=~\"$server\", container_label_cc_bdp_lain_deployd_pg_namespace=~\"$namespace\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\", instance=~\"$server\",container_label_cc_bdp_lain_deployd_pg_namespace=~\"$namespace\",container_label_cc_bdp_lain_deployd_pg_name=~\"$name\"}[5m]) * 100",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\", instance=~\"$server\",container_label_cc_bdp_lain_deployd_pg_namespace=~\"$namespace\",container_label_cc_bdp_lain_deployd_pg_name=~\"$name\"}",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"\", instance=~\"$server\", container_label_cc_bdp_lain_deployd_pg_namespace=~\"$namespace\",container_label_cc_bdp_lain_deployd_pg_name=~\"$name\"}[5m]) * 8",
     "legendFormat": "{{instance}} {{name}} {{interface}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\", instance=~\"$server\", container_label_cc_bdp_lain_deployd_pg_namespace=~\"$namespace\",container_label_cc_bdp_lain_deployd_pg_name=~\"$name\"}[5m]) * 8",
     "legendFormat": "{{instance}} {{name}} {{interface}}"
    }
   ]
  }
 ]
}