{
 "title": "Kafka Exporter Overview",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_consumergroup_current_offset, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   },
   {
    "name": "consumergroup",
    "label": "ConsumerGroup",
    "query": "label_values(kafka_consumergroup_current_offset{instance='$instance',topic!='__consumer_offsets',topic=\"$topic\"}, consumergroup)"
   }
  ]
 },
 "panels": [
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\",consumergroup=~\"$consumergroup\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Kafka Topic Current Offset",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{instance=\"$instance\", topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{$topic}"
    }
   ]
  },
  {
   "title": "Kafka Topic Partitions",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{instance=\"$instance\", topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{$topic}"
    }
   ]
  },
  {
   "title": "Message in per seconds",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=\"$instance\", topic=~\"$topic\"}[2m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  partition",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\", consumergroup =~\"$consumergroup\"}) by (consumergroup, topic, partition) ",
     "legendFormat": "{{consumergroup}}-{{partition}}-(topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message consume per seconds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{instance=~'$instance',topic=~\"$topic\",consumergroup=~\"$consumergroup\"}[5m])) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group TOP10",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(kafka_consumergroup_lag{instance=\"$instance\",consumergroup!='logstash',consumergroup!~\"console.*\"}) by (consumergroup, topic))",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  }
 ]
}