{
 "title": "Lain Container View(DO NOT SAVE)",
 "description": "Mainly for Lain",
 "tags": [
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "query": "statsd.*" }
  ]
 },
 "panels": [
  {
   "title": "QPS in PRD env",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "scaleToSeconds(sumSeries(statsd.dialogue-manager.dialogue-manager.kafka.message.processed.QUESTION.count.count), 1)"
    }
   ]
  },
  {
   "title": "Error Counter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "statsd.$Namespace.$Namespace.grpc.server.*.*.*.*.error_count.count"
    }
   ]
  },
  {
   "title": "RPS for Target NameSpace Service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "scaleToSeconds(statsd.$Namespace.$Namespace.grpc.server.*.*.*.request.count.count, 1)"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", name!=\"swarm-agent.service\", name!=\"swarm-manager.service\", name!=\"calico-libnetwork\", name!=\"cadvisor.service\", name!=\"calico-node\", name!=\"rebellion.service\", container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}[1m])) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "statsd.$Namespace.$Namespace.jvm.*.blocked.count"
    },
    {
     "target": "statsd.$Namespace.$Namespace.jvm.*.runnable.count"
    }
   ]
  },
  {
   "title": "question queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "statsd.dialogue-manager.dialogue-manager.count.questions.in_queue.count"
    }
   ]
  },
  {
   "title": "JVM non-heap used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "statsd.$Namespace.$Namespace.jvm.*.non-heap.used"
    }
   ]
  },
  {
   "title": "JVM heap used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "statsd.$Namespace.$Namespace.jvm.*.heap.used"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\",container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}[1m] ) )) * 8",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"$Namespace\"}[1m] ) )) * 8",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "GRPC Request Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "statsd.treasure-server.treasure-server.grpc.client.manifest.ManifestService.*.*.error_count.count"
    },
    {
     "target": "statsd.kbqa-server.kbqa-server.grpc.client.manifest.*.*.request.error_count.count"
    },
    {
     "target": "statsd.trade-server.trade-server.grpc.client.manifest.*.*.request.error_count.count"
    }
   ]
  },
  {
   "title": "External Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "statsd.$Namespace.$Namespace.failure.call.*.count"
    }
   ]
  },
  {
   "title": "Internal Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "statsd.$Namespace.$Namespace.error.internal_error.count"
    }
   ]
  },
  {
   "title": "latency p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "statsd.trade-server.trade-server.grpc.*.*.*.*.*.p99"
    }
   ]
  }
 ]
}