{
 "title": "Node Exporter(Compare）",
 "description": "Dashboard to view multiple servers",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_boot_time, instance)"
   },
   {
    "name": "device",
    "query": "label_values(node_disk_writes_completed, device)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu{instance=~\"$node\",mode=\"user\"}[5m])) by (instance)  + avg(irate(node_cpu{instance=~\"$node\",mode=\"system\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}  cpu_used_percent"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit", "label": "% used_percent" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active{instance=~\"$node\"}/node_memory_MemTotal{instance=~\"$node\"}",
     "legendFormat": "{{ instance }} {{ }}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_free{instance=~'$node',device !~'tmpfs',device!~'by-uuid', mountpoint!~'.*docker.*'} / node_filesystem_size{instance=~'$node',device !~'tmpfs',device!~'by-uuid', mountpoint!~'.*docker.*'})",
     "legendFormat": "{{ instance }} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{instance=~'$node', device!~'dm-.*', device=~\"$device\"}[5m])",
     "legendFormat": "{{ instance }} {{device}}_reads"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed{instance=~'$node', device!~'dm-.*', device=~\"$device\"}[5m])",
     "legendFormat": "{{ instance }} {{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    {
     "format": "bytes",
     "label": "Bytes/second read (-) / write (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_sectors_read{instance=~'$node', device!~'dm-.*'}[5m]) * 512",
     "legendFormat": "{{ instance }} {{device}} reads"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    {
     "format": "bytes",
     "label": "Bytes/second read (-) / write (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_sectors_written{instance=~'$node', device!~'dm-.*'}[5m]) * 512",
     "legendFormat": "{{ instance }}{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Utilization per Device",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{instance=~\"$node\", device!~'dm-.*', device=~\"$device\"}[5m])/10",
     "legendFormat": "{{ instance }} {{device}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches{instance=~\"$node\"}[5m])",
     "legendFormat": "{{ instance }} context switches"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{instance=~'$node', device=~'eth.*'}[5m])*8",
     "legendFormat": "{{ instance }}  {{device}} in"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes{instance=~'$node', device=~'eth.*'}[5m])*8",
     "legendFormat": "{{ instance }}  {{device}}_out"
    }
   ]
  },
  {
   "title": "Netstat Tcp CurrEstab",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "{{ instance }} established"
    }
   ]
  },
  {
   "title": "文件描述符",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "{{ instance }} FD Allocated"
    }
   ]
  },
  {
   "title": "UDP Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "{{ instance }} Udp_InDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node\"}[5m])",
     "legendFormat": "{{ instance }}  Udp_InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node\"}[5m])",
     "legendFormat": "{{ instance }}  Udp_OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node\"}[5m])",
     "legendFormat": "{{ instance }}  Udp_NoPorts"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$node\"} - node_nf_conntrack_entries{instance=~\"$node\"}",
     "legendFormat": "{{ instance }}  free"
    }
   ]
  }
 ]
}