{
 "title": "oppo",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo\",name=~\"oppo.worker.*\"}[1m])) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo\",name=~\"oppo.worker.*\"}) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "consume",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-marketing-avenue.*trigger.consume.record.count.count, 1), 2)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-recommendation-*.*trigger.consume.record.count.count, 1), 2)"
    }
   ]
  },
  {
   "title": "Marketing-ServiceReport pipeline",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "scaleToSeconds(statsd.oppo.service-report-trigger.consume.record.count.count, 1)"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.service-report-trigger.parse.event.failed.miss.count, 1)"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.service-report-trigger.unneeded.handle.count, 1)"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.service-report-trigger.schedule.delay.count.count, 1)"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.service-report-action.task.executed.count.count, 1)"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.service-report-action.produce.record.count.count, 1)"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.service-report-trigger.schedule.select metric, 1)"
    }
   ]
  },
  {
   "title": "trigger/schedule delay count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-marketing-avenue.*-trigger.trigger.delay.count.count, 1), 2)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-recommendation-avenue.*-trigger.trigger.delay.count.count, 1), 2)"
    }
   ]
  },
  {
   "title": "produce/taskExecute count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-marketing-avenue.*action.produce.record.count.count, 1), 2, 3, 4)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-recommendation-avenue.*action.produce.record.count.count, 1), 2, 3, 4)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-recommendation-trade.*action.produce.record.count.count, 1), 2, 3, 4)"
    }
   ]
  },
  {
   "title": "rate limit drop",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.*trigger.rate.limit.drop.count, 1), 2)"
    }
   ]
  },
  {
   "title": "job failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.*action.delay.job.failed.count.count, 1), 2)"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.*action.redis.*.*.count.count, 1), 2, 4, 5, 6)"
    }
   ]
  },
  {
   "title": "rate limit after",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.rate.limit.after.count, 1)"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.no-order-try-trigger.rate.limit.after.count, 1)"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.marketing-inquiry-retrieve-trigger.rate.limit.after.count, 1)"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.proposed-dialogue-trigger.rate.limit.after.count, 1)"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.marketing-service-report-trigger.rate.limit.after.count, 1)"
    }
   ]
  },
  {
   "title": "grpc",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "scaleToSeconds(statsd.oppo.no-order-try-action.grpc.client.trade.TradeService_GetRecentTrades.request.count.count, 1)"
    },
    {
     "target": "statsd.oppo.no-order-try-action.grpc.client.trade.TradeService_GetRecentTrades.request.error_count.count"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.inquiry-tailing-action.grpc.client.trade.TradeService_GetRecentTrades.request.count.count, 1)"
    },
    {
     "target": "statsd.oppo.inquiry-tailing-action.grpc.client.trade.TradeService_GetRecentTrades.request.error_count.count"
    },
    {
     "target": "scaleToSeconds(statsd.oppo.marketing-inquiry-retrieve-action.grpc.client.trade.TradeService_GetRecentTrades.request.count.count, 1)"
    }
   ]
  },
  {
   "title": "grpc time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "statsd.oppo.inquiry-tailing-action.grpc.client.trade.TradeService_GetRecentTrades.request_time.mean"
    },
    {
     "target": "statsd.oppo.no-order-try-action.grpc.client.trade.TradeService_GetRecentTrades.request_time.mean"
    }
   ]
  }
 ]
}