{
 "title": "oppo",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "WORKER_TRIGGER", "query": "statsd.oppo.*trigger" },
   { "name": "WORKER_ACTION", "query": "statsd.oppo.*action" }
  ]
 },
 "panels": [
  {
   "title": "系统CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "推荐-及时追尾 CPU 使用情况",
     "type": "graph",
     "description": "recommend-InquiryTailing CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-recommend-avenue\",name=~\"oppo-recommend-avenue.worker.inquiry-tailing.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "推荐-询单挽回 CPU使用情况",
     "type": "graph",
     "description": "reommend-noOrderTry CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-recommend-avenue\",name=~\"oppo-recommend-avenue.worker.no-order-try.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "推荐-尺码回复后推荐 CPU使用情况",
     "type": "graph",
     "description": "size-query CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-recommendation-active\",name=~\"oppo-recommendation-active.worker.size.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "推荐-用户付款 CPU使用情况",
     "type": "graph",
     "description": "Buyer CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-recommend-trade\",name=~\"oppo-recommend-trade.worker.buyer.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "统一版-聊天记录 CPU 使用情况",
     "type": "graph",
     "description": "avenue-alliance CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-avenue\",name=~\"oppo-avenue.worker.avenue.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "客服号-买家付款 CPU 使用情况",
     "type": "graph",
     "description": "aicrm-BuyerPay CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-aicrm\",name=~\"oppo-aicrm.worker.aicrm-buyer-pay.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "对话-自学习建议话术收集 CPU 使用情况",
     "type": "graph",
     "description": "dialogue-propose CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo\",name=~\"oppo.worker.proposed-dialogue.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "工单 CPU 使用情况",
     "type": "graph",
     "description": "workOrder CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-action\",name=~\"oppo-marketing-action.worker.work-order.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "营销-询单挽回 CPU 使用情况",
     "type": "graph",
     "description": "marketing-InquiryRetrieve CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-avenue\",name=~\"oppo-marketing-avenue.worker.inquiry-retrieve.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "营销-服务报表 CPU 使用情况",
     "type": "graph",
     "description": "marketing-ServiceReport CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-avenue\",name=~\"oppo-marketing-avenue.worker.service-report.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "营销-同意退换 CPU 使用情况",
     "type": "graph",
     "description": "marketing-RefundAgreement CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-trade-refund\",name=~\"oppo-marketing-trade-refund.worker.refund-agreement.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "营销-催付款 CPU 使用情况",
     "type": "graph",
     "description": "marketing-PayRequest CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-trade\",name=~\"oppo-marketing-trade.worker.payment-request.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "营销-催好评（确认收货）CPU 使用情况",
     "type": "graph",
     "description": "marketing-RateRequest CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-trace\",name=~\"oppo-marketing-trace.worker.rate-request.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "营销-物流签收 CPU 使用情况",
     "type": "graph",
     "description": "marketing-TraceSigned CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-trace\",name=~\"oppo-marketing-trace.worker.trace-signed.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "足迹-用户浏览记录收集 内存使用情况（上限3G）",
     "type": "graph",
     "description": "miles-Footprint CPU Usage",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_cpu_user_seconds_total{image!=\"\", container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-recommendation-active\",name=~\"oppo-recommendation-active.worker.footprint.*\"}[1m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "系统内存 Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "推荐-及时追尾 内存使用情况（上限3G）",
     "type": "graph",
     "description": "recommend-InquiryTailing Memery Usage",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-recommend-avenue\",name=~\"oppo-recommend-avenue.worker.inquiry-tailing.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "推荐-询单挽回 内存使用情况（上限3G）",
     "type": "graph",
     "description": "reommend-noOrderTry Memery Usage",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-recommend-avenue\",name=~\"oppo-recommend-avenue.worker.no-order-try.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "推荐-尺码回复后推荐（上限3G）",
     "type": "graph",
     "description": "Size-Query Memory Usage",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-recommendation-active\",name=~\"oppo-recommendation-active.worker.size.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "推荐-用户付款 内存使用情况（上限3G）",
     "type": "graph",
     "description": "Buyer Memory Usage",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-recommend-trade\",name=~\"oppo-recommend-trade.worker.buyer.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "统一版-聊天记录 内存使用情况（上限3G）",
     "type": "graph",
     "description": "avenue Memery Usage",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-avenue\",name=~\"oppo-avenue.worker.avenue.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "客服号-买家付款 内存使用情况（上限3G）",
     "type": "graph",
     "description": "oppo-aicrm.worker.aicrm-buyer-pay.* Memery Usage",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-aicrm\",name=~\"oppo-aicrm.worker.aicrm-buyer-pay.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "对话-自学习建议话术收集（上限3G）",
     "type": "graph",
     "description": "Dialogue-Propose  Memory Usage",
     "gridPos": { "h": 7, "w": 3, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo\",name=~\"oppo.worker.proposed-dialogue.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "工单 内存使用情况（上限3G）",
     "type": "graph",
     "description": "workOrder Memery Usage",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-action\",name=~\"oppo-marketing-action.worker.work-order.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "营销-询单挽回 内存使用情况（上限3G）",
     "type": "graph",
     "description": "marketing-InquiryRetrieve Memory Usage",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-avenue\",name=~\"oppo-marketing-avenue.worker.inquiry-retrieve.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "营销-服务报表 内存使用情况（上限3G）",
     "type": "graph",
     "description": "marketing-ServiceReport Memory Usage",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-avenue\",name=~\"oppo-marketing-avenue.worker.service-report.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "营销-同意退换 内存使用情况（上限3G）",
     "type": "graph",
     "description": "marketing-RefundAgreement Memory Usage",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-trade-refund\",name=~\"oppo-marketing-trade-refund.worker.refund-agreement.*\"}) by (name))",
       "legendFormat": "{{name}}",
       "target": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo\",name=~\"oppo.worker.payment-request.*\"}) by (name))"
      }
     ]
    },
    {
     "title": "营销-催付款 内存使用情况（上限3G）",
     "type": "graph",
     "description": "marketing-PaymentRequest Memory Usage",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-trade\",name=~\"oppo-marketing-trade.worker.payment-request.*\"}) by (name))",
       "legendFormat": "{{name}}",
       "target": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo\",name=~\"oppo.worker.payment-request.*\"}) by (name))"
      }
     ]
    },
    {
     "title": "营销-催好评（确认收货） 内存使用情况（上限3G）",
     "type": "graph",
     "description": "marketing-RateRequest",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-trace\",name=~\"oppo-marketing-trace.worker.rate-request.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "营销-物流签收 内存使用情况（上限3G）",
     "type": "graph",
     "description": "marketing-TraceSigned",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-marketing-trace\",name=~\"oppo-marketing-trace.worker.trace-signed.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "足迹-用户浏览记录收集 内存使用情况（上限3G）",
     "type": "graph",
     "description": "miles-footprint",
     "gridPos": { "h": 7, "w": 3, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",  container_label_cc_bdp_lain_deployd_pg_namespace=\"oppo-recommendation-active\",name=~\"oppo-recommendation-active.worker.footprint.*\"}) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "业务事件总延时（trigger下发时间-事件源发生时间）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "推荐-及时追尾",
   "type": "singlestat",
   "description": "recommend-InquiryTailing trigger 下发实际延迟时间\n(trigger下发时间-dialogue时间-商家配置延时)",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-recommend-avenue.inquiry-tailing-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "推荐-询单挽回",
   "type": "singlestat",
   "description": "reommend-noOrderTry trigger下发实际延时\n(trigger下发时间-dialogue时间-商家配置延时)",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-recommend-avenue.no-order-try-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "推荐-尺码回复后推荐",
   "type": "singlestat",
   "description": "reommend-sizeQuery trigger下发实际延时\n(trigger下发时间-dialogue时间-商家配置延时)",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-recommendation-active.size-query-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "推荐-买家付款",
   "type": "singlestat",
   "description": "reommend-buyerPay trigger下发实际延时\n(trigger下发时间-dialogue时间-商家配置延时)",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-recommend-trade.buyer-pay-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "统一版-聊天记录",
   "type": "singlestat",
   "description": "avenue-trigger 下发实际延时\n(trigger下发时间-dialogue时间-商家配置延时)",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-avenue.avenue-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "客服号-买家付款",
   "type": "singlestat",
   "description": "aicrm-buyerPay trigger下发实际延时\n(trigger下发时间-dialogue时间-默认延时)",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-aicrm.aicrm-buyer-pay-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "问答-建议话术收集",
   "type": "singlestat",
   "description": "dialogue-propose trigger下发实际延时\n(trigger下发时间-dialogue时间-10min默认延时)",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo.proposed-dialogue-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "工单",
   "type": "singlestat",
   "description": "workOrder-trigger 下发实际延时\n(trigger下发时间-dialogue时间-商家配置延时)",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-marketing-action.work-order-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "营销-询单挽回",
   "type": "singlestat",
   "description": "marketing-InquiryRetrieve trigger 下发实际延时\n(trigger下发时间-dialogue时间-商家配置延时)",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-marketing-avenue.inquiry-retrieve-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "营销-催付款",
   "type": "singlestat",
   "description": "marketing-PaymentRequest trigger 下发实际延时\n(trigger下发时间-dialogue时间)",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-marketing-trade.payment-request-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "营销-同意退换",
   "type": "singlestat",
   "description": "marketing-RefundAgreement-trigger下发实际延时\n(trigger下发时间-dialogue时间-商家配置延时)",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-marketing-trade-refund.refund-agreement-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "营销-退换理由修改",
   "type": "singlestat",
   "description": "refund-reason-change-trigger 下发实际延时\n(trigger下发时间-dialogue时间-商家配置延时)",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-marketing-trade-refund.refund-reason-change-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "营销-催好评（确认收货）",
   "type": "singlestat",
   "description": "marketing-RateRequest trigger 下发实际延时\n(trigger下发时间-dialogue时间)",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-marketing-trace.rate-request-action.execute.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "营销-签收",
   "type": "singlestat",
   "description": "marketing-TraceSigned trigger 下发实际延时\n(trigger下发时间-dialogue时间-商家配置延时)",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-marketing-trace.trace-signed-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "足迹-收集用来浏览记录",
   "type": "singlestat",
   "description": "footprint-trigger下发实际延时\n(trigger下发时间-事件发生时间)",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-recommendation-active.footprint-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  {
   "title": "营销-服务报表",
   "type": "singlestat",
   "description": "marketing-ServiceReport trigger 下发实际延时\n(trigger下发时间-dialogue时间-商家配置延时)",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 11 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "statsd.oppo-marketing-avenue.service-report-action.trigger.delay.miss.milli.mean"
    }
   ]
  },
  { "title": "报警监控指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "kafka-lag：dialogue-conversation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(burrowx.ka.dialogue-conversation.oppo_dialogue_group_1.lag, 1), 'recommend-InquiryTailing')"
    },
    {
     "target": "alias(scaleToSeconds(burrowx.ka.dialogue-conversation.oppo_dialogue_group_2.lag, 1), 'reommend-noOrderTry')"
    },
    {
     "target": "alias(scaleToSeconds(burrowx.ka.dialogue-conversation.oppo_dialogue_group_3.lag, 1), 'dialogue-Propose')"
    },
    {
     "target": "alias(scaleToSeconds(burrowx.ka.dialogue-conversation.oppo_dialogue_group_4.lag, 1), 'marketing-InquiryRetrieve')"
    },
    {
     "target": "alias(scaleToSeconds(burrowx.ka.dialogue-conversation.oppo_dialogue_group_5.lag, 1), 'marketing-ServiceReport')"
    }
   ]
  },
  {
   "title": "kafka-lag：TradeEvent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(burrowx.ka.TradeEvent.oppo_trade_group_1.lag, 1), 'buyerPay')"
    },
    {
     "target": "alias(scaleToSeconds(burrowx.ka.TradeEvent.oppo_trade_group_2.lag, 1), 'buyerStepPay')"
    },
    {
     "target": "alias(scaleToSeconds(burrowx.ka.TradeEvent.oppo_trade_group_3.lag, 1), 'refundAgreement')"
    },
    {
     "target": "alias(scaleToSeconds(burrowx.ka.TradeEvent.oppo_trade_group_4.lag, 1), 'paymentRequest')"
    },
    {
     "target": "alias(scaleToSeconds(burrowx.ka.TradeEvent.oppo_trade_group_5.lag, 1), 'rateRequest')"
    },
    {
     "target": "alias(scaleToSeconds(burrowx.ka.TradeEvent.oppo_trade_group_6.lag, 1), 'REFUND_REASON_CHANGE')"
    },
    {
     "target": "alias(scaleToSeconds(burrowx.ka.TradeEvent.oppo_trade_aicrm_1.lag, 1), 'aicrm-BuyerPay')"
    }
   ]
  },
  {
   "title": "kafka-lag：dialogue-active-trigger(10s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(burrowx.ka.dialogue-active-trigger.oppo_dialogue_group_6.lag, 10), 'dialogue-active: size-query')"
    },
    {
     "target": "alias(scaleToSeconds(burrowx.ka.opportunity-recommendation.knight_knight_oppo_group.lag, 10), 'knight')"
    }
   ]
  },
  {
   "title": "consume:dialogue-conversation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_TRIGGER.consume.record.count.count, 1), 2)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_TRIGGER.parse.event.buyernick.not.match.count, 1), 2, 5, 6, 7)"
    }
   ]
  },
  {
   "title": "rate drop",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.*trigger.rate.limit.drop.count, 1), 2)"
    }
   ]
  },
  {
   "title": "kafka-lag：dialogue-alliance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(burrowx.ka.dialogue-alliance.oppo_dialogue_alliance_1.lag, 1), 'dialogue-alliance')"
    }
   ]
  },
  {
   "title": "kafka-lag：TraceEvent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(burrowx.ka.TraceEvent.oppo_trace_group_1.lag, 1), 'trace-Signed')"
    }
   ]
  },
  {
   "title": "tradeType filter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-*.*.filter.tradeType.drop.count, 1), 1, 2)"
    }
   ]
  },
  {
   "title": "业务数据pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "recommend-InquiryTailing 漏斗",
     "type": "graph",
     "description": "推荐-及时追尾 数据处理漏斗",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.consume.record.count.count, 1), 'consume count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.store.config.miss.count, 1), 'storeConfig miss')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.store.disable.count, 1), 'storeConfig diable(miss)')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.parse.event.buyernick.null.count, 1), 'buyernick null')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.parse.event.failed.miss.count, 1), 'parse failed(buyrnick null)')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.parse.event.success.count, 1), 'parse success')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.schedule.spuid.null.count, 1), 'spuId null')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.cancel.delay.count.count, 1), 'cancel count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.trigger.delay.count.count, 1), 'will schedule count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.schedule.delay.count.count, 1), 'schedule count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-recommend-avenue.inquiry-tailing-action.produce.record.count.count, 1), 'produce count')"
      }
     ]
    },
    {
     "title": "reommend-noOrderTry 漏斗",
     "type": "graph",
     "description": "推荐-询单挽回 数据处理漏斗",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(scaleToSeconds(statsd.oppo.no-order-try-trigger.consume.record.count.count, 1), 'consume count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.no-order-try-trigger.store.disable.count, 1), 'storeConfig disable(miss)')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.no-order-try-trigger.parse.event.failed.miss.count, 1), 'parse failed(buyernick null)')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.no-order-try-trigger.parse.event.success.count, 1), 'parse success')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.no-order-try-trigger.cancel.delay.count.count, 1), 'cancel count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.no-order-try-trigger.trigger.delay.count.count, 1), 'will schedule count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.no-order-try-trigger.schedule.delay.count.count, 1), 'schedule count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-recommend-avenue.no-order-try-action.produce.record.count.count, 1), 'produce count')"
      }
     ]
    },
    {
     "title": "recommend-size-quiry 漏斗(10s)",
     "type": "graph",
     "description": "业务数据pipeline.",
     "gridPos": { "h": 7, "w": 3, "x": 6, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo-recommendation-active.size-query-trigger.consume.record.count.count, 10), 2, 3, 4)"
      },
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo-recommendation-active.size-query-trigger.store.disable.count, 10), 2, 3, 4)"
      },
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo-recommendation-active.size-query-trigger.parse.event.failed.miss.count, 10), 2, 3, 4, 5)"
      },
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo-recommendation-active.size-query-trigger.trigger.delay.count.count, 10), 2, 3)"
      },
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo-recommendation-active.size-query-trigger.schedule.delay.count.count, 10), 2, 3)"
      },
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo-recommendation-active.size-query-action.produce.record.count.count, 10), 2, 3, 4)"
      }
     ]
    },
    {
     "title": "recommend-buyerPay 漏斗",
     "type": "graph",
     "description": "推荐-买家付款 数据处理漏斗",
     "gridPos": { "h": 7, "w": 3, "x": 9, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo.buyer-pay-trigger.consume.record.count.count, 1), 3, 4)"
      },
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo.buyer-pay-trigger.store.config.miss.count, 1), 3, 4, 5)"
      },
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo.buyer-pay-trigger.store.disable.count, 1), 3, 4, 5)"
      },
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo.buyer-pay-trigger.store.delaySecond.invalid.count, 1), 3, 4, 5)"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.buyer-pay-trigger.trigger.delay.count.count, 1), 'will.trigger.count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.buyer-pay-trigger.schedule.delay.count.count, 1), 'trigger.count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.buyer-pay-action.produce.record.count.count, 1), 'produce count')"
      },
      {
       "target": "statsd.oppo.buyer.select metric"
      }
     ]
    },
    {
     "title": "marketing-InquiryRetrieve 漏斗",
     "type": "graph",
     "description": "营销-询单挽回 数据处理 漏斗",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-avenue.inquiry-retrieve-trigger.consume.record.count.count, 1), 'consume count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-avenue.inquiry-retrieve-trigger.store.disable.count, 1), 'storeConfig disable(miss)')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-avenue.inquiry-retrieve-trigger.parse.event.failed.miss.count, 1), 'parse failed(buyrnick null)')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.marketing-inquiry-retrieve-trigger.parse.event.success.count, 1), 'parse success')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-avenue.inquiry-retrieve-trigger.cancel.delay.count.count, 1), 'cancel count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.marketing-inquiry-retrieve-trigger.trigger.delay.count.count, 1), 'will schedule count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-avenue.inquiry-retrieve-trigger.schedule.delay.count.count, 1), 'schedule count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-avenue.inquiry-retrieve-action.produce.record.count.count, 1), 'produce count')"
      }
     ]
    },
    {
     "title": "marketing-payment-request 漏斗",
     "type": "graph",
     "description": "营销-催付款 数据处理漏斗",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo-marketing-trade.payment-request-trigger.consume.record.count.count, 1), 3, 4)"
      },
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo.payment-request-trigger.select metric, 1), 3, 4, 5)"
      },
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo.payment-request-trigger.select metric, 1), 3, 4, 5)"
      },
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo.payment-request-trigger.select metric, 1), 3, 4, 5)"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-trade.payment-request-trigger.trigger.delay.count.count, 1), 'will.trigger.count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-trade.payment-request-trigger.schedule.delay.count.count, 1), 'trigger.count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-trade.payment-request-action.produce.record.count.count, 1), 'produce count')"
      }
     ]
    },
    {
     "title": "marketing-ServiceRepot 漏斗",
     "type": "graph",
     "description": "营销-服务报表 数据处理 漏斗",
     "gridPos": { "h": 7, "w": 3, "x": 18, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-avenue.service-report-trigger.consume.record.count.count, 1), 'consume count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-avenue.service-report-trigger.parse.event.failed.miss.count, 1), 'parse failed(buyrnick null)')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.marketing-service-report-trigger.parse.event.success.count, 1), 'parse success')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-avenue.service-report-trigger.unneeded.handle.count, 1), 'unneeded handle')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.marketing-service-report-trigger.trigger.delay.count.count, 1), 'will schedule count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-avenue.service-report-trigger.schedule.delay.count.count, 1), 'schedule count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo-marketing-avenue.service-report-action.produce.record.count.count, 1), 'produce count')"
      }
     ]
    },
    {
     "title": "propose-dialogue 漏斗",
     "type": "graph",
     "description": "自学习-话术收集 数据处理漏斗",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(scaleToSeconds(statsd.oppo.proposed-dialogue-trigger.consume.record.count.count, 1), 'consume count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.proposed-dialogue-trigger.parse.event.failed.miss.count, 1), 'parse failed(buyrnick null)')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.proposed-dialogue-trigger.parse.event.success.count, 1), 'parse success')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.proposed-dialogue-trigger.cancel.delay.count.count, 1), 'cancel count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.proposed-dialogue-trigger.schedule.start.count, 1), 'isTargetEvent')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.proposed-dialogue-trigger.trigger.delay.count.count, 1), 'will schedule count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.proposed-dialogue-trigger.schedule.delay.count.count, 1), 'schedule count')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.proposed-dialogue-action.produce.record.count.count, 1), 'produce count')"
      }
     ]
    }
   ]
  },
  {
   "title": "业务粒度指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "schedule",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.schedule.delay.count.count, 1), 'recommend-InquiryTailing')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.no-order-try-trigger.schedule.delay.count.count, 1), 'reommend-noOrderTry')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.marketing-inquiry-retrieve-trigger.schedule.delay.count.count, 1), 'marketing-InquiryRetrieve')"
      }
     ]
    },
    {
     "title": "cancel",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(scaleToSeconds(statsd.oppo.inquiry-tailing-trigger.cancel.delay.count.count, 1), 'recommend-InquiryTailing')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.no-order-try-trigger.cancel.delay.count.count, 1), 'reommend-noOrderTry')"
      },
      {
       "target": "alias(scaleToSeconds(statsd.oppo.marketing-inquiry-retrieve-trigger.cancel.delay.count.count, 1), 'marketing-InquiryRetrieve')"
      }
     ]
    },
    {
     "title": "action produce",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(scaleToSeconds(statsd.oppo.*action.produce.record.count.count, 1), 2)"
      }
     ]
    },
    {
     "title": "action delay",
     "type": "graph",
     "description": "action 执行延时时间",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(statsd.oppo.*action.execute.delay.miss.milli.mean, 2)"
      }
     ]
    },
    {
     "title": "parser delay",
     "type": "graph",
     "description": "解析dialogue records 延时时间",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(statsd.oppo.*trigger.parse.event.time.miss.mean, 2)"
      }
     ]
    },
    {
     "title": "店铺配置 平均 delaySeconds",
     "type": "graph",
     "description": "店铺配置 平均 delaySecond",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(statsd.oppo.*action.execute.delay.fact.milli.mean, 2)"
      }
     ]
    }
   ]
  },
  { "title": "依赖服务指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Trade\\Item\\abserver some error",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-*.*.*.call.*.null.count, 1), 2, 3, 5, 6)"
    }
   ]
  },
  {
   "title": "Trade\\AbServer\\Manifest\\Hela Service Request count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-*.*.grpc.client.com.leyantech.hela.proto.Hela*.request.count.count, 1), 2, 5, 6, 7)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-*.*.grpc.client.*.*.request.count.count, 1), 2, 5, 6, 7)"
    }
   ]
  },
  {
   "title": "grpc requestTime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(statsd.oppo-*.*.grpc.client.com.leyantech.hela.proto.HelaStoreConfigService*.request_time.mean, 2, 5, 6, 7)"
    },
    {
     "target": "aliasByNode(statsd.oppo-*.*.grpc.client.*.*.request_time.mean, 2, 5, 6, 7)"
    }
   ]
  },
  { "title": "业务异常指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "delay job failed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-*.*-action.delay.job.failed.count.count, 1), 2, 3, 4, 5)"
    }
   ]
  },
  {
   "title": "redis miss",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-*.*.redis.miss.data.count.count, 1), 2, 3, 4)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo-*.*.redis.error.count, 1), 2, 3, 4)"
    }
   ]
  },
  {
   "title": "TRIGGER some wrong",
   "type": "graph",
   "description": "trigger 异常.",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "statsd.oppo.$WORKER_TRIGGER.record.value.null.select metric"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_TRIGGER.rate.limit.drop.count, 1), 2, 4, 5)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_TRIGGER.parse.event.buyernick.null.count, 1), 2, 5, 6)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_TRIGGER.parse.event.buyernick.not.match.count, 1), 2, 5, 6, 7)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_TRIGGER.store.config.miss.count, 1), 2, 3, 4, 5)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_TRIGGER.parse.store.config.failed.count, 1), 2, 4, 5, 6)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_TRIGGER.store.delaySecond.invalid.count, 1), 2, 4, 5)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_TRIGGER.runner.process.failed.count, 1), 2, 3, 4, 5)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_TRIGGER.schedule.delay.failed.count.count, 1), 2, 3, 4, 5)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_ACTION.delay.job.failed.count.count, 1), 2, 4, 5)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_ACTION.redis.miss.data.count.count, 1), 2, 3, 4)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_ACTION.json.event.fail.count, 1), 2, 3, 4, 5)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(statsd.oppo.$WORKER_ACTION.produce.record.failed.count.count, 1), 2, 3, 4, 5)"
    }
   ]
  },
  {
   "title": "。。。",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "schedule spuId null",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "statsd.oppo.inquiry-tailing-trigger.schedule.spuid.null.count"
      },
      {
       "target": "statsd.oppo.no-order-try-trigger.schedule.spuid.null.count"
      },
      {
       "target": "statsd.oppo.proposed-dialogue-trigger.schedule.start.count.count"
      }
     ]
    },
    {
     "title": "input records",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "statsd.oppo.inquiry-tailing-trigger.in.record.count"
      },
      {
       "target": "statsd.oppo.no-order-try-trigger.in.record.count"
      },
      {
       "target": "statsd.oppo.marketing-inquiry-retrieve-trigger.in.record.count"
      },
      {
       "target": "statsd.oppo.proposed-dialogue-trigger.in.record.count"
      }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } }
 ]
}